# Generated by Django 5.2.6 on 2025-12-10 07:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_list', models.TextField(verbose_name='Ваши навыки')),
                ('organization_name', models.CharField(max_length=255, verbose_name='Наименование организации')),
                ('organization_inn', models.CharField(max_length=12, verbose_name='ИНН организации')),
                ('organization_website', models.URLField(blank=True, verbose_name='Сайт организации')),
                ('solution_name', models.CharField(max_length=255, verbose_name='Краткое наименование решения')),
                ('solution_description', models.TextField(verbose_name='Описание предлагаемого решения')),
                ('solution_experience', models.TextField(verbose_name='Релевантный опыт применения')),
                ('budget', models.CharField(default=0, max_length=8, verbose_name='Бюджет')),
                ('contact_first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('contact_last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('contact_middle_name', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В обработке'), ('approved', 'Одобрена'), ('rejected', 'Отклонена')], default='new', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('requirements', models.JSONField(blank=True, default=list, verbose_name='Требования к ресурсам')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
    ]
