# Generated by Django 5.2.6 on 2025-12-11 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_application'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='requirements',
        ),
        migrations.AddField(
            model_name='application',
            name='requirement_name',
            field=models.TextField(default='Цена ресурса', max_length=255, verbose_name='Название ресурса'),
        ),
        migrations.AddField(
            model_name='application',
            name='requirement_price',
            field=models.CharField(default=0, verbose_name='Цена ресурса'),
        ),
    ]
