# Generated by Django 5.2.6 on 2025-12-11 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_application_requirements_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='requirement_name',
            field=models.TextField(default='', max_length=255, verbose_name='Название ресурса'),
        ),
    ]
