# Generated by Django 5.2.6 on 2025-12-12 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_application_requirement_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='budget',
        ),
        migrations.AlterField(
            model_name='application',
            name='contact_email',
            field=models.EmailField(default='ya@gmail.com', max_length=254, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='application',
            name='contact_first_name',
            field=models.CharField(default='Тимур', max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='application',
            name='contact_last_name',
            field=models.CharField(default='Шокиров', max_length=100, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='application',
            name='contact_phone',
            field=models.CharField(default='+79879879292', max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='application',
            name='organization_inn',
            field=models.CharField(default='1000000000', max_length=12, verbose_name='ИНН организации'),
        ),
        migrations.AlterField(
            model_name='application',
            name='organization_name',
            field=models.CharField(default='NewOrg', max_length=255, verbose_name='Наименование организации'),
        ),
        migrations.AlterField(
            model_name='application',
            name='organization_website',
            field=models.URLField(blank=True, default='http://NewOrg.com', verbose_name='Сайт организации'),
        ),
        migrations.AlterField(
            model_name='application',
            name='skill_list',
            field=models.TextField(default='JS, REACT, TypeScript', verbose_name='Ваши навыки'),
        ),
        migrations.AlterField(
            model_name='application',
            name='solution_description',
            field=models.TextField(default='-', verbose_name='Описание предлагаемого решения'),
        ),
        migrations.AlterField(
            model_name='application',
            name='solution_experience',
            field=models.TextField(default='-', verbose_name='Релевантный опыт применения'),
        ),
        migrations.AlterField(
            model_name='application',
            name='solution_name',
            field=models.CharField(default='-', max_length=255, verbose_name='Краткое наименование решения'),
        ),
    ]
