# Generated by Django 5.2.6 on 2025-12-12 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_application_budget_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='requirement_name',
            field=models.TextField(default='Ноут', max_length=255, verbose_name='Название ресурса'),
        ),
        migrations.AlterField(
            model_name='application',
            name='requirement_price',
            field=models.CharField(default=10000, verbose_name='Цена ресурса'),
        ),
    ]
