# Generated by Django 5.1.1 on 2026-02-16 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_application_requirement_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='requirement_price',
            field=models.CharField(default=10000, max_length=255, verbose_name='Цена ресурса'),
        ),
    ]
