# Generated by Django 5.1.1 on 2026-02-26 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_application_requirement_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название проекта')),
                ('description', models.TextField(verbose_name='Описание проекта')),
                ('team_activities', models.TextField(blank=True, verbose_name='Чем планирует заниматься команда')),
                ('work_conditions', models.TextField(blank=True, verbose_name='Условия работы')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Бюджет проекта')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('active', 'Активный'), ('in_progress', 'В работе'), ('completed', 'Завершен'), ('on_hold', 'Приостановлен'), ('cancelled', 'Отменен')], default='draft', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_created_projects', to=settings.AUTH_USER_MODEL, verbose_name='Создатель проекта')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст комментария')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_project_comments', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='main.projectcomment', verbose_name='Ответ на')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='project_files/%Y/%m/%d/', verbose_name='Файл')),
                ('filename', models.CharField(max_length=255, verbose_name='Имя файла')),
                ('file_size', models.IntegerField(verbose_name='Размер файла (байт)')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Описание')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='main.project', verbose_name='Проект')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_uploaded_files', to=settings.AUTH_USER_MODEL, verbose_name='Загрузил')),
            ],
            options={
                'verbose_name': 'Файл проекта',
                'verbose_name_plural': 'Файлы проекта',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(blank=True, max_length=200, verbose_name='Название навыка')),
                ('level_requirement', models.CharField(blank=True, choices=[('beginner', 'Начинающий'), ('junior', 'Junior'), ('middle', 'Middle'), ('senior', 'Senior'), ('expert', 'Эксперт')], max_length=20, verbose_name='Требуемый уровень')),
                ('work_condition', models.CharField(blank=True, help_text='Например: "Работа в выходные", "Командировки"', max_length=500, verbose_name='Условие работы')),
                ('people_count', models.PositiveIntegerField(default=1, verbose_name='Количество человек')),
                ('is_mandatory', models.BooleanField(default=True, verbose_name='Обязательное')),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Для ресурсных требований', max_digits=12, null=True, verbose_name='Стоимость')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='main.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Требование к участнику',
                'verbose_name_plural': 'Требования к участникам',
                'ordering': ['-is_mandatory', 'skill_name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидает ответа'), ('accepted', 'Принято'), ('declined', 'Отклонено'), ('cancelled', 'Отменено')], default='pending', max_length=20, verbose_name='Статус')),
                ('message', models.TextField(blank=True, verbose_name='Сопроводительное сообщение')),
                ('invited_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата приглашения')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата ответа')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_project_invitations', to='main.application', verbose_name='Заявка')),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_sent_invitations', to=settings.AUTH_USER_MODEL, verbose_name='Пригласил')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='main.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Приглашение',
                'verbose_name_plural': 'Приглашения',
                'ordering': ['-invited_at'],
                'unique_together': {('project', 'application')},
            },
        ),
        migrations.CreateModel(
            name='ProjectParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('skills', models.TextField(blank=True, verbose_name='Навыки')),
                ('requirements', models.TextField(blank=True, verbose_name='Требования к ресурсам')),
                ('requirement_price', models.CharField(blank=True, max_length=255, verbose_name='Цена ресурсов')),
                ('role', models.CharField(default='Участник', max_length=200, verbose_name='Роль в проекте')),
                ('status', models.CharField(choices=[('active', 'Активный'), ('inactive', 'Неактивный'), ('left', 'Покинул проект')], default='active', max_length=20, verbose_name='Статус')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата присоединения')),
                ('left_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата ухода')),
                ('contribution_description', models.TextField(blank=True, verbose_name='Описание вклада')),
                ('rating', models.PositiveSmallIntegerField(blank=True, help_text='Оценка от 1 до 5', null=True, verbose_name='Оценка')),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_project_memberships', to='main.application', verbose_name='Заявка')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='main.project', verbose_name='Проект')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_participating_projects', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Участник проекта',
                'verbose_name_plural': 'Участники проекта',
                'unique_together': {('project', 'application')},
            },
        ),
    ]
