# Generated by Django 5.1.1 on 2026-02-26 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_customuser_options_alter_customuser_managers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
