# Generated by Django 5.1.1 on 2026-03-12 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_application_solution_description_and_more'),
        ('main', '0010_alter_customuser_options_alter_customuser_managers'),
    ]

    operations = [
    ]
