# Generated by Django 5.1.1 on 2026-03-12 12:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_merge_20260312_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='contact_email',
            field=models.EmailField(max_length=254, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='application',
            name='contact_first_name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='application',
            name='contact_last_name',
            field=models.CharField(max_length=100, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='application',
            name='contact_phone',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть в формате: '+7XXXXXXXXXX'", regex='^\\+7\\d{10}$')], verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='application',
            name='organization_inn',
            field=models.CharField(max_length=12, verbose_name='ИНН организации'),
        ),
        migrations.AlterField(
            model_name='application',
            name='organization_name',
            field=models.CharField(max_length=255, verbose_name='Наименование организации'),
        ),
        migrations.AlterField(
            model_name='application',
            name='organization_website',
            field=models.URLField(blank=True, verbose_name='Сайт организации'),
        ),
        migrations.AlterField(
            model_name='application',
            name='requirement_name',
            field=models.TextField(blank=True, default='', verbose_name='Названия ресурсов'),
        ),
        migrations.AlterField(
            model_name='application',
            name='requirement_price',
            field=models.TextField(blank=True, default='', verbose_name='Цены ресурсов'),
        ),
        migrations.AlterField(
            model_name='application',
            name='skill_list',
            field=models.TextField(blank=True, default='', verbose_name='Ваши навыки'),
        ),
        migrations.AlterField(
            model_name='application',
            name='team_role',
            field=models.CharField(blank=True, choices=[('visionary', 'Генератор идей'), ('implementer', 'Исполнитель'), ('leader', 'Лидер'), ('organizer', 'Организатор'), ('analyst', 'Аналитик'), ('communicator', 'Коммуникатор'), ('perfectionist', 'Контролер качества'), ('resource_investigator', 'Исследователь ресурсов'), ('developer', 'Разработчик'), ('designer', 'Дизайнер'), ('project_manager', 'Проектный менеджер'), ('other', 'Другое')], max_length=50, null=True, verbose_name='Роль в команде'),
        ),
        migrations.AlterField(
            model_name='application',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
