# Generated by Django 5.1.1 on 2026-03-18 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_application_contact_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={},
        ),
        migrations.AlterModelOptions(
            name='projectrequirement',
            options={},
        ),
        migrations.AddField(
            model_name='project',
            name='keywords',
            field=models.CharField(blank=True, help_text='Введите через запятую', max_length=500, verbose_name='Ключевые слова'),
        ),
        migrations.AddField(
            model_name='projectrequirement',
            name='belbin_role',
            field=models.CharField(blank=True, choices=[('implementer', 'Исполнитель'), ('coordinator', 'Координатор'), ('shaper', 'Формирователь'), ('plant', 'Генератор идей'), ('resource_investigator', 'Разведчик'), ('teamworker', 'Душа команды'), ('monitor_evaluator', 'Аналитик'), ('completer_finisher', 'Педантичность'), ('specialist', 'Специалист')], max_length=30, verbose_name='Роль по Белбину'),
        ),
        migrations.AlterField(
            model_name='projectrequirement',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='projectrequirement',
            name='skill_name',
            field=models.CharField(max_length=200, verbose_name='Название навыка'),
        ),
        migrations.AlterField(
            model_name='projectrequirement',
            name='work_condition',
            field=models.CharField(blank=True, max_length=500, verbose_name='Условие работы'),
        ),
    ]
