# Generated by Django 5.1.1 on 2026-03-18 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_project_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectrequirement',
            name='level_requirement',
            field=models.CharField(blank=True, choices=[('beginner', 'Начинающий'), ('middle', 'Продвинутый'), ('expert', 'Эксперт')], max_length=20, verbose_name='Требуемый уровень'),
        ),
    ]
